### ISSUE TITLE
Installation on Mac?

### ISSUE THREAD

**Issue by mathicm** [Fluorescence-Tools/Olga#12]
Hi,
Just wonder if you would be able to provide Olga installation for Mac?
Thank you
Mathi

**Comment by mdimura** [comment]
Hi! Unfortunately, I don't have a Mac at my disposal, and I also have zero experience building software for Mac. However, to my knowledge, it should be quite straightforward to build Olga for Mac. One would probably need to build some of the dependencies, but it should work.

**Comment by mathicm** [comment]
Thank you for your response.
