### ISSUE TITLE
How to generate the input trajectory file (.dcd)?

### ISSUE THREAD

**Issue by mayeshh** [Fluorescence-Tools/Olga#13]
I am trying to use Olga to troubleshoot a smFRET experiment... in the future, I will first use Olga *then* do the labeling.

Will you please clarify the following: 

1) Is the .pdb output file from NMSim the topology input file for Olga?
2) How can I generate the .dcd trajectory file? 

I apologize if these questions are naive... I have read your 2020 publication but I am still unclear on the process. 

Thanks in advance for any help you can give!

**Comment by mdimura** [comment]
1. You only need the first frame from the NMSim trajectory. Just extract the first model from the .PDB trajectory via notepad.
2. You can use any trajectory processing tool at hand, e.g. VMD can do it via GUI.

And it is perfectly fine to use Olga before, after, or in parallel with experiments. I hope this helps!

**Comment by mayeshh** [comment]
Thank you for your fast response! 

I did eventually figure out how to convert to .dcd using `mdconvert`, the MDTraj command line tool, but I was using the wrong topology file (the original PDB file). Extracting the first frame from the trajectory file fixed that. 

Thanks so much!
