### ISSUE TITLE
Support for intermolecular FRET pairs

### ISSUE THREAD

**Issue by mayeshh** [Fluorescence-Tools/Olga#14]
Does Olga support labeling schemes *between* molecules? 

I see two possible approaches to this:

1. load two trajectories into Olga (not sure if it's possible)
2. perform the simulation myself on a larger system (NMSim has a size limit) then load it into Olga

I am attempting to model smFRET experiments with two singly-labeled molecules i.e., sigma70 of *E. coli* RNA polymerase (donor) and DNA template/non-template (acceptor). Since NMSim doesn't like multiple subunits, I am not sure how I can generate the trajectory file. I realize that this is a loaded question, as MD is an entire field, but maybe you can point me in the right direction?

**Comment by tpeulen** [comment]
Olga support intra-molecular labeling schemes and searches for optimal intra and inter-molecular FRET pairs. 

However, does not sample conformational ensembles that you'd need to select an optimal FRET pair for a docking problem. You need to solve your docking problem in another software and use Olga for scoring the docked structures or to select optimal FRET pairs.

You could use the Förster-radius of your dye pairs to restrain your docking solutions, e.g., in FPS, and search for FRET pairs using Olga.
